### ISSUE TITLE
在TimeMixer.py中249行的函数forecast中出现报错

### ISSUE THREAD

**Issue by YanDong1112** [kwuking/TimeMixer#1]
![image](https://github.com/kwuking/TimeMixer/assets/67414760/d8a1315b-423e-403e-bccb-8507c8cf3be2)
可以看到，经过for loop之后的x只有两个维度，那么再经过下一句会报错。
![image](https://github.com/kwuking/TimeMixer/assets/67414760/92759c1e-9314-43f8-9ec5-ad02ac3e9ba5)
同时再往下一句的normalize中，normalize_layer的层数是否有len(x_enc)，经过查看层数只有down_sampling_layers+1，这里却是self.normalize_layer[i]，i最后会达到15，而脚本给出的参数down_sampling_layers是3（使用的为ETTm1数据文件及其脚本给出的参数），这也是对应不上的。
![image](https://github.com/kwuking/TimeMixer/assets/67414760/b1313f2c-c409-458a-b1db-21f26b997b90)

**Comment by kwuking** [comment]
您好，请问您执行的是ETTm1的脚本以及其对的数据嘛，我本地用CPU和GPU都进行了测试是没有问题的可以正常运行，数据加载肯定是要三维的B,T,N，正常不会是只有两个维度的
![image](https://github.com/kwuking/TimeMixer/assets/7886135/fe7d8f98-c610-4c8a-ad7a-1db2fd2d448f)

![image](https://github.com/kwuking/TimeMixer/assets/7886135/de5f4fa6-0d6b-481f-8bc4-5c1836b9d3d6)
这边down_sampling_layers=3降采样执行3次，再加上原始的时序一共4组数据(96->48->24->12)，batchsize设置的16，我这边直接运行都是没有问题，是否可以提供相应的运行配置信息以及数据信息呢？

**Comment by YanDong1112** [comment]
您好，十分抱歉，刚刚我提出的报错原因已经排查到了，是由于’dowm_sampling_method‘的参数没有设置成’avg‘，导致数据在输入模型的时候没有做downsample处理，使得x_enc成了原始的数据输入，导致在forecast函数中for loop步骤报错，经过修改后是能完成运行的，再次给您说声抱歉，十分不好意思。

**Comment by kwuking** [comment]
> 您好，十分抱歉，刚刚我提出的报错原因已经排查到了，是由于’dowm_sampling_method‘的参数没有设置成’avg‘，导致数据在输入模型的时候没有做downsample处理，使得x_enc成了原始的数据输入，导致在forecast函数中for loop步骤报错，经过修改后是能完成运行的，再次给您说声抱歉，十分不好意思。

非常感谢您对于我们工作的关注，如果我们的工作能够帮助到您，还请您能够引用和推广，再次表示感谢。

**Comment by chuachuachuaXXX** [comment]
请问，从代码里怎么哪里能看出来输入的数据是先经过downsample处理再进入forecast函数的呢，我看model里面forword函数，不是直接把原始数据输入到forecast中吗

**Comment by kwuking** [comment]
> 请问，从代码里怎么哪里能看出来输入的数据是先经过downsample处理再进入forecast函数的呢，我看model里面forword函数，不是直接把原始数据输入到forecast中吗

你好，我们在exp的代码中增加了下采样的相关操作，如下图所示，通过预先的downsample操作生成不同scale的时序：
![image](https://github.com/kwuking/TimeMixer/assets/7886135/6bfa1fcb-de3a-48a0-8b70-032ccb8332b7)

**Comment by chuachuachuaXXX** [comment]
下采样操作中那个函数的输入，batch_x是形状为（B,T,C）的原始数据，batch_y是什么哦

**Comment by kwuking** [comment]
> 下采样操作中那个函数的输入，batch_x是形状为（B,T,C）的原始数据，batch_y是什么哦

batch_y是训练的label，其shape也是B, T, C
