### ISSUE TITLE
周期趋势的分解

### ISSUE THREAD

**Issue by nobodyplayer** [kwuking/TimeMixer#11]
您好，我想知道您在附录里提到的基于DFT增强的分解具体是怎么实现的？需要对每个变量都计算嘛？选最重要的前K个频率又咋选呢？ 有没有代码可以学习一下~

**Comment by kwuking** [comment]
你好我们的TimeMixer.py的代码文件中有提供对应的[基于DFT进行分解的代码](https://github.com/kwuking/TimeMixer/blob/deb92ad7a1182aa6db8cad06d518ecc8e0c2bd43/models/TimeMixer.py#L7C1-L25C33)，您可以参考。

**Comment by nobodyplayer** [comment]
> 你好我们的 TimeMixer.py 的代码文件中有提供对应的[基于DFT进行分解的代码](https://github.com/kwuking/TimeMixer/blob/deb92ad7a1182aa6db8cad06d518ecc8e0c2bd43/models/TimeMixer.py#L7C1-L25C33)，您可以参考。

感谢！之前没注意在这里有，谢谢回复
