### ISSUE TITLE
GELU hard coded

### ISSUE THREAD

**Issue by lzmax888** [kwuking/TimeMixer#12]
Hi,

It seems that the activation func has been hard coded in TimeMixer.py as nn.GELU. I cannot set it by --activation parameter.

Thanks

**Comment by kwuking** [comment]
> Hi,
> 
> It seems that the activation func has been hard coded in TimeMixer.py as nn.GELU. I cannot set it by --activation parameter.
> 
> Thanks

We indeed use GELU as the default activation function, about the design of the [TSLib](https://github.com/thuml/Time-Series-Library/blob/main/models/TimesNet.py).  Thanks for your suggestion, we will consider making this more flexible in future iterations.
