### ISSUE TITLE
请问unified hyperparameter和searched hyperparameter有什么区别呢

### ISSUE THREAD

**Issue by 1353918285** [kwuking/TimeMixer#14]
如题

**Comment by kwuking** [comment]
请参考文章附录E中的相关讨论：
> To ensure a fair comparison between models, we conducted experiments using unified parameters and reported results in the main text, including aligning all the input lengths, batch sizes, and training epochs in all experiments.

>In addition, considering that the reported results in different papers are mostly obtained through hyperparameter search, we provide the experiment results with the full version of the parameter search.
