### ISSUE TITLE
请问这两行代码的作用是什么？

### ISSUE THREAD

**Issue by HuiziLv** [kwuking/TimeMixer#15]
您好，
在TimeMixer.py->class Model(nn.Module)->def forecast(self, x_enc, x_mark_enc, x_dec, x_mark_dec)中，我有两个问题：
![图片](https://github.com/kwuking/TimeMixer/assets/166986447/2316a1c5-db06-4fdd-9902-e9272b42f8fe)
问题1：请问图中328行的x_mark = x_mark.repeat(N, 1, 1)有什么作用？运行后，x_mark的batchsize维度被乘了N，导致我在embedding时，无法执行加法x = self.value_embedding(x) + self.temporal_embedding(x_mark)，因为两个部分的batchsize维度不相等了，前者仍是batchsize，后者则是N*batchsize。所以我不得不注释了这一行代码。。。
问题2：请问图中342行x_list = self.pre_enc(x_list) 有什么作用呀？我感觉是在时间维度做了移动平均和做差，使输出的x_list有了[0][1]两个tuple。我想问一下，如下图所示，将x_list分成两个tuple，x_list[0]和x_list[1]，分别进入embedding和future_multi_mixing是出于什么考虑呢？我好像没有在论文中找到解释，QAQ
![图片](https://github.com/kwuking/TimeMixer/assets/166986447/104f4a6e-1925-4608-921f-f4ecf190a1af)
烦请答疑，非常感谢！

**Comment by kwuking** [comment]
> 问题1：请问图中328行的x_mark = x_mark.repeat(N, 1, 1)有什么作用？

这里是为了处理channel independent操作，因为把输入X的channel维度的N移到了batch上，这里x_mark也需要重复N次对齐；

问题2：请问图中340行x_list = self.pre_enc(x_list) 有什么作用呀？

这里是针对x的输入进行周期趋势的分解，分别进行处理

**Comment by HuiziLv** [comment]
> > 问题1：请问图中328行的x_mark = x_mark.repeat(N, 1, 1)有什么作用？
> 
> 这里是为了处理channel independent操作，因为把输入X的channel维度的N移到了batch上，这里x_mark也需要重复N次对齐；
> 
> > 问题2：请问图中340行x_list = self.pre_enc(x_list) 有什么作用呀？
> 
> 这里是针对x的输入进行周期趋势的分解，分别进行处理

请问您在建模过程中，channel independent是根据效果做出的选择吗？一般来说是0还是1呢？

**Comment by 1353918285** [comment]
请问这里的channel independent借鉴的是哪篇论文呢

**Comment by kwuking** [comment]
> 请问这里的channel independent借鉴的是哪篇论文呢

请参考patchTST（https://arxiv.org/abs/2211.14730）

**Comment by kwuking** [comment]
> > > 问题1：请问图中328行的x_mark = x_mark.repeat(N, 1, 1)有什么作用？
> > 
> > 
> > 这里是为了处理channel independent操作，因为把输入X的channel维度的N移到了batch上，这里x_mark也需要重复N次对齐；
> > > 问题2：请问图中340行x_list = self.pre_enc(x_list) 有什么作用呀？
> > 
> > 
> > 这里是针对x的输入进行周期趋势的分解，分别进行处理
> 
> 请问您在建模过程中，channel independent是根据效果做出的选择吗？一般来说是0还是1呢？

通常针对具有复杂关系的多元变量，例如PEMS数据集等采用channel dependent；其余场景采用channel independent方案较好；具体可以参考这个论文https://arxiv.org/abs/2304.05206

**Comment by HuiziLv** [comment]
> 通常针对具有复杂关系的多元变量，例如PEMS数据集等采用channel dependent；其余场景采用channel independent方案较好；具体可以参考这个论文https://arxiv.org/abs/2304.05206
好的，感谢。如果我想通过变量ABC来预测ABC+D的变化，由于输入没有D，是不是只能选择channel dependent了？

**Comment by kwuking** [comment]
> > 通常针对具有复杂关系的多元变量，例如PEMS数据集等采用channel dependent；其余场景采用channel independent方案较好；具体可以参考这个论文https://arxiv.org/abs/2304.05206
> 
> 好的，感谢。如果我想通过变量ABC来预测ABC+D的变化，由于输入没有D，是不是只能选择channel dependent了？

你好，如果是协变量预测（如上所述，用变量ABC来预测ABC+D的）确实是需要选择channel dependent

**Comment by HuiziLv** [comment]
> 你好，如果是协变量预测（如上所述，用变量ABC来预测ABC+D的）确实是需要选择channel dependent

感谢您的耐心回答，对我帮助很大。我没有问题啦~
