### ISSUE TITLE
Perhaps the logic errors in the code

### ISSUE THREAD

**Issue by AlienAssassin** [kwuking/TimeMixer#17]
在下面这段代码中，```x_mark = x_mark.repeat(N, 1, 1)``` 似乎无法实现真正意义上的对齐。如果batch size > 1, 直接对x_mark进行repeat实际上并不能和 ```x = x.permute(0, 2, 1).contiguous().reshape(B * N, T, 1)``` 中的reshape操作对应上。这将导致如果送入模型不同batch szie大小的数据（例如bs = 64, bs = 32），并且他们中有一条公共的数据，那么两个batch size中对这条公共数据预测得到的结果将是不一致的。

将其改为 ```x_mark = x_mark.unsqueeze(1).repeat(1, N, 1, 1).reshape(B * N, T, -1)``` 可产生正确预测结果。

```
x_list = []
        x_mark_list = []
        if x_mark_enc is not None:
            for i, x, x_mark in zip(range(len(x_enc)), x_enc, x_mark_enc):
                B, T, N = x.size()
                x = self.normalize_layers[i](x, 'norm')
                if self.channel_independence == 1:
                    x = x.permute(0, 2, 1).contiguous().reshape(B * N, T, 1)
                x_list.append(x)
                x_mark = x_mark.repeat(N, 1, 1)
                x_mark_list.append(x_mark)
```

**Comment by kwuking** [comment]
非常感谢你的建议，我会尽快进行测试，如果确认无误，我会更新相应内容，再次感谢你的发现。
