### ISSUE TITLE
设置 args.features = 'MS'时程序错误

### ISSUE THREAD

**Issue by nightknight2017** [kwuking/TimeMixer#18]
在测试'electricity.csv'数据集时，设置args.features = 'MS'，args.target = 'OT'，args.enc_in = 321， args.dec_in = 321，args.c_out = 1，其余参数采用默认参数，程序会报错：RuntimeError: shape '[32, 1, 96]' is invalid for input of size 986112

**Comment by kwuking** [comment]
> 在测试'electricity.csv'数据集时，设置args.features = 'MS'，args.target = 'OT'，args.enc_in = 321， args.dec_in = 321，args.c_out = 1，其余参数采用默认参数，程序会报错：RuntimeError: shape '[32, 1, 96]' is invalid for input of size 986112

你好咱们设置args.target = 'OT'，args.c_out = 1，是需要预测其中一条特性的序列嘛

**Comment by nightknight2017** [comment]
> > 在测试'electricity.csv'数据集时，设置args.features = 'MS'，args.target = 'OT'，args.enc_in = 321， args.dec_in = 321，args.c_out = 1，其余参数采用默认参数，程序会报错：RuntimeError: shape '[32, 1, 96]' is invalid for input of size 986112
> 
> 你好咱们设置args.target = 'OT'，args.c_out = 1，是需要预测其中一条特性的序列嘛

我是想先测试多对一的预测问题，就先在这个case上测试了下，发现有问题

**Comment by kwuking** [comment]
> > > 在测试'electricity.csv'数据集时，设置args.features = 'MS'，args.target = 'OT'，args.enc_in = 321， args.dec_in = 321，args.c_out = 1，其余参数采用默认参数，程序会报错：RuntimeError: shape '[32, 1, 96]' is invalid for input of size 986112
> > 
> > 
> > 你好咱们设置args.target = 'OT'，args.c_out = 1，是需要预测其中一条特性的序列嘛
> 
> 我是想先测试多对一的预测问题，就先在这个case上测试了下，发现有问题

目前TimeMixer还不支持协变量预测的模式，如果是做协变量预测可以参考我们另外一个工作[TimeXer: Empowering Transformers for Time Series Forecasting with Exogenous Variables](https://arxiv.org/abs/2402.19072)

**Comment by kwuking** [comment]
> 请问现在支持协变量预测的模式了吗

你好，目前是支持的引入一部分协变量进行预测，可以参考我们的readme更新的内容。
