### ISSUE TITLE
在短期预测读取m4数据

### ISSUE THREAD

**Issue by FeiLis** [kwuking/TimeMixer#19]
在短期预测读取m4数据
training_values = np.array([v for v in dataset.values[dataset.groups == self.seasonal_patterns]],dtype=np.float32)报错

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (23000,) + inhomogeneous part.
想问一下怎么解决呀

**Comment by FeiLis** [comment]
@kwuking 
![Uploading 1713669139077.png…]()

**Comment by FeiLis** [comment]
@kwuking 
![1713669139077](https://github.com/kwuking/TimeMixer/assets/167526464/83b85a76-569c-4f94-9691-11db689c05e6)

**Comment by kwuking** [comment]
请问你执行的是哪一个脚本，是怎么执行的？这段代码我测试了没有问题

**Comment by wangshuruii** [comment]
> @kwuking ![1713669139077](https://private-user-images.githubusercontent.com/167526464/324220842-83b85a76-569c-4f94-9691-11db689c05e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTY5MzUsIm5iZiI6MTcxNTA5NjYzNSwicGF0aCI6Ii8xNjc1MjY0NjQvMzI0MjIwODQyLTgzYjg1YTc2LTU2OWMtNGY5NC05NjkxLTExZGI2ODljMDVlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxNTQzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjZmZmU5Nzg4YmVkYmJmZDQ0N2VkNGNkNzI2NWZjMGVkN2RjYTY5NzZlYzkxYWU2MTZmM2Q5Y2MxZWQ0NmQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9NaqA-IF26mGm6vPnMPKNmbAei-7BjABR-J6Z70UYdA)

您好，我也遇到了同样的问题，执行的脚本是scripts/short_term_forecast/M4/TimeMixer.sh脚本，环境按照requirements.txt配置。在上述代码位置添加dtype=object后，会产生新的报错：
  File "run.py", line 139, in <module>
    exp.train(setting)
  File "/home/srwang/nlp/TimeMixer/exp/exp_short_term_forecasting.py", line 99, in train
    loss_value = criterion(batch_x, self.args.frequency_map, outputs, batch_y, batch_y_mark)
  File "/home/srwang/anaconda3/envs/timemixer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/srwang/nlp/TimeMixer/utils/losses.py", line 67, in forward
    return 200 * t.mean(divide_no_nan(t.abs(forecast - target),
RuntimeError: The size of tensor a (18) must match the size of tensor b (36) at non-singleton dimension 1

**Comment by kwuking** [comment]
> > @kwuking ![1713669139077](https://private-user-images.githubusercontent.com/167526464/324220842-83b85a76-569c-4f94-9691-11db689c05e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTY5MzUsIm5iZiI6MTcxNTA5NjYzNSwicGF0aCI6Ii8xNjc1MjY0NjQvMzI0MjIwODQyLTgzYjg1YTc2LTU2OWMtNGY5NC05NjkxLTExZGI2ODljMDVlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxNTQzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjZmZmU5Nzg4YmVkYmJmZDQ0N2VkNGNkNzI2NWZjMGVkN2RjYTY5NzZlYzkxYWU2MTZmM2Q5Y2MxZWQ0NmQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9NaqA-IF26mGm6vPnMPKNmbAei-7BjABR-J6Z70UYdA)
> 
> 您好，我也遇到了同样的问题，执行的脚本是scripts/short_term_forecast/M4/TimeMixer.sh脚本，环境按照requirements.txt配置。在上述代码位置添加dtype=object后，会产生新的报错： File "run.py", line 139, in exp.train(setting) File "/home/srwang/nlp/TimeMixer/exp/exp_short_term_forecasting.py", line 99, in train loss_value = criterion(batch_x, self.args.frequency_map, outputs, batch_y, batch_y_mark) File "/home/srwang/anaconda3/envs/timemixer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/home/srwang/nlp/TimeMixer/utils/losses.py", line 67, in forward return 200 * t.mean(divide_no_nan(t.abs(forecast - target), RuntimeError: The size of tensor a (18) must match the size of tensor b (36) at non-singleton dimension 1

看起来是tensor不匹配，您执行的参数脚本可以发一下嘛，是否和提供的脚本中参数一致呢？

**Comment by wangshuruii** [comment]
执行的参数脚本是scripts/short_term_forecast/M4/TimeMixer.sh，和提供的脚本完全一致，具体参数为：
`model_name=TimeMixer

e_layers=4
down_sampling_layers=1
down_sampling_window=2
learning_rate=0.01
d_model=32
d_ff=32
batch_size=16


python -u run.py \
  --task_name short_term_forecast \
  --is_training 1 \
  --root_path ./dataset/m4 \
  --seasonal_patterns 'Monthly' \
  --model_id m4_Monthly \
  --model $model_name \
  --data m4 \
  --features M \
  --e_layers $e_layers \
  --d_layers 1 \
  --factor 3 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --batch_size 128 \
  --d_model $d_model \
  --d_ff 32 \
  --des 'Exp' \
  --itr 1 \
  --learning_rate $learning_rate \
  --train_epochs 50 \
  --patience 20 \
  --down_sampling_layers $down_sampling_layers \
  --down_sampling_method avg \
  --down_sampling_window $down_sampling_window \
  --loss 'SMAPE'`

如果不修改training_values，报错与提问者相同：ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (48000,) + inhomogeneous part.

**Comment by kwuking** [comment]
你好 我更新了M4短程预测的代码以便于更加便利运行，您可以在尝试一下是否可以运行呢

**Comment by wangshuruii** [comment]
感谢您的耐心回答，使用更新后的代码M4可以正常运行了~

**Comment by mz24cn** [comment]
只要把numpy版本降到1.23.0就可以了
