### ISSUE TITLE
The “freeze_support()” line can be omitted if the program is not going to be frozen to produce an executable.

### ISSUE THREAD

**Issue by Xin-Ray** [kwuking/TimeMixer#21]
raise RuntimeError(‘’'
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == ‘__main__‘:
                freeze_support()
                ...
        The “freeze_support()” line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by kwuking** [comment]
Hi, the reason for this error is due to using multi-processing for data loading locally. When running in a local non-GPU environment, please set the num_workers parameter to 0 and the use_gpu parameter to false.

**Comment by Xin-Ray** [comment]
Thank you for your response, but I didn't find the num_workers parameter and use_gpu parameter. could you tell me the location of these parameters? Thank you.

**Comment by Xin-Ray** [comment]
thank you, I found them. this program run successfully.
