### ISSUE TITLE
Forecastability的计算

### ISSUE THREAD

**Issue by YunMeiGongRen** [kwuking/TimeMixer#22]
你好，我想知道原文中数据集的Forecastability是怎么计算出来的。我尝试过使用'data_analysis.py'中'forecastabilty_moving‘和’forecastabilty‘函数，但得到的结果与原文相差很大。
想问一下有更详细的计算过程代码吗？烦请答疑，万分感谢

**Comment by kwuking** [comment]
> 你好，我想知道原文中数据集的Forecastability是怎么计算出来的。我尝试过使用'data_analysis.py'中'forecastabilty_moving‘和’forecastabilty‘函数，但得到的结果与原文相差很大。 想问一下有更详细的计算过程代码吗？烦请答疑，万分感谢

你好，我们是采用的随机抽样和滑窗采样的方式进行的测试，不同的策略可能会导致结果的不同。

**Comment by Irelandr** [comment]
您好，请问可以给出具体的计算执导吗？关于输入输出定义和分析等等，论文中的数字是怎么算出来的呢？
