### ISSUE TITLE
关于模型benchmark脚本文件

### ISSUE THREAD

**Issue by Diroooomy** [kwuking/TimeMixer#23]
在论文中看到长期预测有两组实验，一组是Unified hyperparameter results，另一组是hyperparameter searching results
第一个问题：第一组的统一超参数的概念不是很明白，不同模型之间的超参数能统一吗
第二个问题：代码仓库中长期预测只看到unify的脚本文件，超参数搜索是更改了哪些参数，从结果上来看，是否是改变了输入的序列长度seq_len，可否提供完整的脚本文件。
万分感谢

**Comment by kwuking** [comment]
你好，统一超参数实验是在保持相同的输入长度，以及在固定范围内的其他超参数进行的的对比测试，可以参考论文中实验章节以及附录的描述；超参数搜索则是对超参数进行了搜索以后得到每个模型的最优参数组合进行的调优实验，考虑到可能因为过度调参带来的影响，我们推荐统一超参数的实验。如果您想要进行调参，可以尝试加大seql_len以及layer的层数和下采样的次数，此外包括时序分解以及采样方式，我们也提供了包含moving_avg分解以及时频分解和卷积采样等多种方式。

**Comment by Diroooomy** [comment]
感谢解答
