### ISSUE TITLE
关于channel_independence

### ISSUE THREAD

**Issue by 1353918285** [kwuking/TimeMixer#27]
当channel_independence设置为0的时候，程序报错，xmark和x的第一维度不匹配，无法合并，请问你们是如何处理的
![TG5TPA5 }ZI5)J76P5G5FP8](https://github.com/kwuking/TimeMixer/assets/62321103/a035bae7-64ee-456a-a8c7-96b26d32ab63)

**Comment by kwuking** [comment]
你好 请问执行的是哪个数据集的脚本呢
