### ISSUE TITLE
Pycharm运行run.py，数据集ETTm1，出错

### ISSUE THREAD

**Issue by congraty** [kwuking/TimeMixer#29]
![屏幕截图 2024-06-04 155254](https://github.com/kwuking/TimeMixer/assets/45891211/c24b52da-221c-4a02-9e2c-eeeb4b2c5204)
下载的源码只修改了这几个参数：  
  parser.add_argument('--model', type=str, default='TimeMixer',help='model name, options: [Autoformer, Transformer, TimesNet]')
    # data loader
parser.add_argument('--data', type=str, default='ETTm1', help='dataset type')
parser.add_argument('--root_path', type=str, default='./data/ETT/', help='root path of the data file')
parser.add_argument('--data_path', type=str, default='ETTm1.csv', help='data file')
其余未修改，想问下是哪里出了问题？

**Comment by Aaron-yhj** [comment]
您好，想问问您是如何解决这个问题的呢？

**Comment by 805ya** [comment]
我也遇到一样的问题，请问解决了吗

**Comment by Aaron-yhj** [comment]
其实就是运行参数的问题，您对照他ETTm1运行的sh文件中，一个一个的设置就没问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月16日(周二) 晚上7:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kwuking/TimeMixer] Pycharm运行run.py，数据集ETTm1，出错 (Issue #29)




 
我也遇到一样的问题，请问解决了吗
