### ISSUE TITLE
normalize

### ISSUE THREAD

**Issue by chuachuachuaXXX** [kwuking/TimeMixer#3]
你好，我想问一下源码里自定义的Normalize方法的作用，为什么数据在norm之后，代码的最后部分还需要denorm。一般的laynorm不需要这么做。

**Comment by kwuking** [comment]
> 你好，我想问一下源码里自定义的Normalize方法的作用，为什么数据在norm之后，代码的最后部分还需要denorm。一般的laynorm不需要这么做。

你好，我们这里的norm是为了进行数据的平稳化操作，并非单纯的进行数据标准化，可以参考论文Non-stationary Transformers: Exploring the Stationarity in Time Series Forecasting (https://arxiv.org/abs/2205.14415)
