### ISSUE TITLE
数据地址：不让访问google drive 的解法

### ISSUE THREAD

**Issue by wentixiaogege** [kwuking/TimeMixer#30]
https://www.kaggle.com/datasets/wentixiaogege/time-series-dataset

如上，不谢

**Comment by kwuking** [comment]
你好 请问是数据没法下载嘛？上面的链接我可以打开，如果无法访问google drive的话，可以尝试使用外网操作。

**Comment by kwuking** [comment]
> https://www.kaggle.com/datasets/wentixiaogege/time-series-dataset
> 
> 如上，不谢

I see，感谢你的建议，我会把这个加入readme，再次表示感谢~
