### ISSUE TITLE
更换自己的数据，遇到的问题。AttributeError: 'Namespace' object has no attribute 'frequency_map'

### ISSUE THREAD

**Issue by warmful-sun** [kwuking/TimeMixer#31]
您好，拜读过您的文章，十分钦佩。但是在更换代码的时候遇到了如下的报错：
Traceback (most recent call last):
  File "D:\TimeMixer-main\run.py", line 140, in <module>
    exp.train(setting)
  File "D:\TimeMixer-main\exp\exp_short_term_forecasting.py", line 101, in train
    loss_value = criterion(batch_x, self.args.frequency_map, outputs, batch_y, batch_y_mark)
AttributeError: 'Namespace' object has no attribute 'frequency_map'

我想实现短期的12步预测，但是未能实现，这是什么问题呢
Namespace(task_name='short_term_forecast', is_training=1, model_id='Data_May', model='TimeMixer', data='custom', root_path='./dataset/WQX/', data_path='Data_May.csv', features='MS', target='OT', freq='t', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=12, seasonal_patterns='Monthly', inverse=False, top_k=5, num_kernels=6, enc_in=6, dec_in=6, c_out=6, d_model=32, n_heads=8, e_layers=4, d_layers=1, d_ff=32, moving_avg=25, factor=3, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, channel_independence=1, decomp_method='moving_avg', use_norm=1, down_sampling_layers=1, down_sampling_window=2, down_sampling_method='avg', use_future_temporal_feature=0, num_workers=0, itr=1, train_epochs=50, batch_size=128, patience=20, learning_rate=0.001, des='test', loss='SMAPE', lradj='TST', pct_start=0.2, use_amp=False, comment='none', use_gpu=False, gpu=0, use_multi_gpu=False, devices='0,1', p_hidden_dims=[128, 128], p_hidden_layers=2)
这是我参数设置，麻烦题主能给解惑，再次感谢！

**Comment by warmful-sun** [comment]
更换自己的数据时

**Comment by kwuking** [comment]
你好 可以使用long-term forecasting的setting进行实验，修改对应数据集和pred len即可；shot-term forecasting目前主要用于M4数据集上，部分setting在其他数据集上不太适用；感谢对于我们的工作关注，如果我们的工作帮助到您，还请引用下我们的工作~

**Comment by splendourbell** [comment]
> 更换自己的数据时
哈哈，这个框架更换数据。。。里面全是耦合

**Comment by kwuking** [comment]
> 你好 可以使用long-term forecasting的setting进行实验，修改对应数据集和pred len即可；shot-term forecasting目前主要用于M4数据集上，部分setting在其他数据集上不太适用；感谢对于我们的工作关注，如果我们的工作帮助到您，还请引用下我们的工作~

请问具体是有什么问题呢，我们这个是参考的thuml组的Time-Series-Library库的框架设计，目前主流时序模型发布都是参考的这个框架，我们目前正致力于将TimeMixer加入亚马逊AWS时序团队的GlounTS项目和neuralforecast项目，您可以关注我们的readme会第一时间更新

**Comment by TrilsKnightley** [comment]
> 更换自己的数据时
hello，可以联系交流一下么。q，2122831576
