### ISSUE TITLE
The question about the forecastability

### ISSUE THREAD

**Issue by mb-Ma** [kwuking/TimeMixer#32]
It seems a counterintuitive phenomenon of forecastability. 

Table 1 shows that the weather and Electricity datasets possess high forecastabilities. In other words, they are easier to predict than these datasets with low forecastability, e.g.,  ETT (4 datasets).  

However, the ETT, traffic datasets have obvious periodic patterns derived from the visualizations and ACF. Especially, it is harder to find the pattern to fit, as shown in Fig 12 of the paper.

Could you provide some insights into the above question?

**Comment by kwuking** [comment]
Thank you very much for your attention to our work. Forecastability is a key issue in time series analysis. Currently, our forecastability calculations are performed through global sampling on the time series. The ETT dataset is actually recognized as one with a higher degree of forecasting difficulty. The visual showcases only display a portion of the content and do not represent the complete time series. Compared to larger datasets such as Electricity and Traffic, the patterns of cycles and trends are more evident, resulting in stronger predictability.

**Comment by mb-Ma** [comment]
How about the weather dataset? No matter the complete or partial time series, there are no obvious cycles or trends.
