### ISSUE TITLE
There are no SOLAR directory files in the dataset

### ISSUE THREAD

**Issue by Zlus-yu** [kwuking/TimeMixer#34]
93/5000
In the dataset compression file you provided, I did not find the solar-energy directory. According to the definition in your program, it should be in the./dataset/solar/ , and there should be a solar_AL.txt file in this directory.
![image](https://github.com/kwuking/TimeMixer/assets/76934917/000f04a2-cdca-42f5-acaf-ed5be9f99431)

**Comment by kwuking** [comment]
Hi, thank you for your interest in our work. You can access the complete dataset through the Google Drive link provided in the README.
