### ISSUE TITLE
python版本，cuda版本

### ISSUE THREAD

**Issue by yslbit** [kwuking/TimeMixer#36]
你好，请问你的python版本，cuda版本是啥，我直接倒在第一步了。。。

**Comment by kwuking** [comment]
python3.8 cuda版本建议使用11.3

**Comment by yslbit** [comment]
好吧，感谢你的回复，但是如果你配置了环境，你就会发现，CUDA11.3版本下，没有与之兼容的pytorch 1.7.1
![Snipaste_2024-06-17_09-56-06](https://github.com/kwuking/TimeMixer/assets/77875279/0beb9f19-45a5-4db9-8b0c-6ac9bbf74969)

**Comment by kwuking** [comment]
> 好吧，感谢你的回复，但是如果你配置了环境，你就会发现，CUDA11.3版本下，没有与之兼容的pytorch 1.7.1（requirement.txt：torch==1.7.1）![Snipaste_2024-06-17_09-56-06](https://private-user-images.githubusercontent.com/77875279/340156822-0beb9f19-45a5-4db9-8b0c-6ac9bbf74969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTY3NDUsIm5iZiI6MTcxODYxNjQ0NSwicGF0aCI6Ii83Nzg3NTI3OS8zNDAxNTY4MjItMGJlYjlmMTktNDVhNS00ZGI5LThiMGMtNmFjOWJiZjc0OTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA5MjcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxN2VkMGUyYmVlNzhlZjE5NDNkYTExZDE0ZWNjMGFlMzE3ZWY5MDcxYjg5MzhkMDE4NTFjMmEzOTk5Njg4NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zHOW6VgNXNcZEK6M6M8aIIDuiD0RSkjVUg3qiwc4Xgs)

你好如果是使用pytorch 1.7.1建议使用cuda10.2；如果想要使用cuda11 建议使用torch1.11的版本
