### ISSUE TITLE
有关数据处理相关问题

### ISSUE THREAD

**Issue by warmful-sun** [kwuking/TimeMixer#37]
作者您好，如果我将数据进行模态分解，直接将分解后的数据选择M，即多变量预测多变量，最后将预测结果相加，能否实现预测效果的准确性提升呢，这样可不可行呢？在这里再次感谢作者的源码分享。

**Comment by kwuking** [comment]
你好，感谢对于我们工作的关注，请问模态分解具体是什么意思呢？目前如果要使用多变量预测，请关闭channel independent功能。

**Comment by warmful-sun** [comment]
谢谢作者回复，我已知晓该问题，再次感谢您的回复。
