### ISSUE TITLE
预测结果滞后性

### ISSUE THREAD

**Issue by boris-lb** [kwuking/TimeMixer#38]
感谢作者开源算法，实际在个人数据集上，训练好之后，测试集推理结果都存在滞后性，如下图所示，请教一下，有什么好的解决思路？
![image](https://github.com/kwuking/TimeMixer/assets/39977498/a6b58ddd-063f-4e19-ae72-b792f301af90)

**Comment by kwuking** [comment]
你好，感谢对于我们工作的关注，请问你是用的什么数据集呢？是否使用了时间特征，可以考虑使用我们最新的future temporal features for prediction功能进行尝试~

**Comment by boris-lb** [comment]
> 你好，感谢对于我们工作的关注，请问你是用的什么数据集呢？是否使用了时间特征，可以考虑使用我们最新的future temporal features for prediction功能进行尝试~

用的是我自己的数据集，使用了时间特征，根据数据采样频率，freq为t，加入future temporal features for prediction后还是同样的结果，不只是我们的这个算法，包括Autoformer等其他的变种算法，mse很小，但预测结果都存在滞后性的问题。

**Comment by boris-lb** [comment]
> > > 你好，感谢对于我们工作的关注，请问你是用的什么数据集呢？是否使用了时间特征，可以考虑使用我们最新的future temporal features for prediction功能进行尝试~
> > 
> > 
> > 用的是我自己的数据集，使用了时间特征，根据数据采样频率，freq为t，加入future temporal features for prediction后还是同样的结果，不只是我们的这个算法，包括Autoformer等其他的变种算法，mse很小，但预测结果都存在滞后性的问题。
> 
> 使用xgboost也遇到了明显的滞后性问题，是否是数据集本身不可预测

工业生产数据，不同特征之间也有相关性，理论上来说应该可预测的。

**Comment by kwuking** [comment]
你好，这个可能需要检查一下是否是数据处理上存在问题呢？如果普遍所有模型都存在规律性的显著滞后，可能是数据处理上存在一定偏移。
