### ISSUE TITLE
seq_len为奇数的时候__multi_scale_process_inputs有问题

### ISSUE THREAD

**Issue by aesdhj** [kwuking/TimeMixer#4]
down_sampling_window=2的时候，如果seq_len=45（奇数），x_enc用torch.nn.AvgPool1d或者torch.nn.MaxPool1d向下采样的长度22，
x_mark_enc向下采样的时候x_mark_enc_mark_ori[:, ::self.configs.down_sampling_window, :] 长度23，会不一致把

**Comment by kwuking** [comment]
> down_sampling_window=2的时候，如果seq_len=45（奇数），x_enc用torch.nn.AvgPool1d或者torch.nn.MaxPool1d向下采样的长度22， x_mark_enc向下采样的时候x_mark_enc_mark_ori[:, ::self.configs.down_sampling_window, :] 长度23，会不一致把

你好，因为默认下采样窗口是2，如果是奇数的话，建议需要修改下采样的窗口尺寸以及下采样层数，例如45的长度，下采样窗口为2，层数也为2即可。
