### ISSUE TITLE
parser.add_argument('--inverse', action='store_true', help='inverse output data', default=True)

### ISSUE THREAD

**Issue by warmful-sun** [kwuking/TimeMixer#40]
作者您好，我再归一化时遇到了这个问题，当我选择True时，程序提示错误，这是因为什么呢？
Traceback (most recent call last):
  File "D:\ZJT\Apredict_suanfa\TimeMixer-main\run.py", line 143, in <module>
    exp.test(setting)
  File "D:\ZJT\Apredict_suanfa\TimeMixer-main\exp\exp_long_term_forecasting.py", line 278, in test
    input = test_data.inverse_transform(input.squeeze(0)).reshape(shape)
ValueError: cannot select an axis to squeeze out which has size not equal to one
期待作者您的回复，感谢！

**Comment by Zlus-yu** [comment]
这里使用input.squeeze(0)压缩input维度时，第一个维度要求为1，不为1的话会报上述错误。这里input的shape为[batch_size, seq_len, feature_dims]，看程序data_factory.py文件，第35行注释：# bsz=1 for evaluation，但是程序里定义的是batch_size = args.batch_size，不清楚这里是不是bug，评估测试将.batch_size改为1应该就行了，没测试过。至于压缩维度，我想应该是test_data.inverse_transform逆转换，scaler在拟合时使用的二维数据，因此输入也要求二维数组
