### ISSUE TITLE
多特征预测

### ISSUE THREAD

**Issue by hczs** [kwuking/TimeMixer#41]
您好，非常感谢您的工作！
我想要使用您的模型做多特征预测，比如说PEMS08数据集，我想要使用流量和速度两个特征，有什么好办法吗？需要对模型做哪些修改工作？（数据集已处理好，不知道模型部分如何修改）
非常感谢！

**Comment by kwuking** [comment]
你好目前pems是支持多变量联合预测的，您只需要关闭channel_independent即可

**Comment by hczs** [comment]
> 你好目前pems是支持多变量联合预测的，您只需要关闭channel_independent即可，此外多元时间预测可以关注我们另一个工作[iTransformer: Inverted Transformers Are Effective for Time Series Forecasting](https://github.com/thuml/iTransformer)，协变量预测可以关注[TimeXer: Empowering Transformers for Time Series Forecasting with Exogenous Variables](https://arxiv.org/abs/2402.19072)。

非常感谢您的回复，但是您目前的代码，模型输入部分都是BTN的形状，参考 data_loader.py 第 746 行，PEMS 系列的数据都是截取了一个特征值用于模型训练，包括输出也是BTN；
也是我第一次没有表述清楚，我想做的是输入是BTND，D是特征数量（包括流量和速度），然后输出也是BTND，D也包括预测的流量和速度数据，现在模型具有这个功能吗？
万分感谢！

**Comment by kwuking** [comment]
> > 你好目前pems是支持多变量联合预测的，您只需要关闭channel_independent即可，此外多元时间预测可以关注我们另一个工作[iTransformer: Inverted Transformers Are Effective for Time Series Forecasting](https://github.com/thuml/iTransformer)，协变量预测可以关注[TimeXer: Empowering Transformers for Time Series Forecasting with Exogenous Variables](https://arxiv.org/abs/2402.19072)。
> 
> 非常感谢您的回复，但是您目前的代码，模型输入部分都是BTN的形状，参考 data_loader.py 第 746 行，PEMS 系列的数据都是截取了一个特征值用于模型训练，包括输出也是BTN； 也是我第一次没有表述清楚，我想做的是输入是BTND，D是特征数量（包括流量和速度），然后输出也是BTND，D也包括预测的流量和速度数据，现在模型具有这个功能吗？ 万分感谢！

是否可以将BTND转换成BT(N*D)的形状呢，BTN中N就是不同变量的数量，我理解和你提到的D是一个概念，这两个维度是可以整合的。

**Comment by hczs** [comment]
> > > 你好目前pems是支持多变量联合预测的，您只需要关闭channel_independent即可，此外多元时间预测可以关注我们另一个工作[iTransformer: Inverted Transformers Are Effective for Time Series Forecasting](https://github.com/thuml/iTransformer)，协变量预测可以关注[TimeXer: Empowering Transformers for Time Series Forecasting with Exogenous Variables](https://arxiv.org/abs/2402.19072)。
> > 
> > 
> > 非常感谢您的回复，但是您目前的代码，模型输入部分都是BTN的形状，参考 data_loader.py 第 746 行，PEMS 系列的数据都是截取了一个特征值用于模型训练，包括输出也是BTN； 也是我第一次没有表述清楚，我想做的是输入是BTND，D是特征数量（包括流量和速度），然后输出也是BTND，D也包括预测的流量和速度数据，现在模型具有这个功能吗？ 万分感谢！
> 
> 是否可以将BTND转换成BT(N*D)的形状呢，BTN中N就是不同变量的数量，我理解和你提到的D是一个概念，这两个维度是可以整合的。

BT(N*D)改成这样子输入，输出再拆成BTND，模型运行效果可以的，也接近论文水平；
不过最终解决办法是在输入和输出加了一个Linear，把特征维度D刷成了1，然后转BT(N*D)，输出的时候再变换回来，这种处理最终模型指标表现也不错。
感谢作者的回复，我的问题已解决，非常感谢！
