### ISSUE TITLE
我也遇到了这个问题，好像是数据量的行数少就会有这个问题

### ISSUE THREAD

**Issue by hushuguo** [kwuking/TimeMixer#42]
我也遇到了这个问题，好像是数据量的行数少就会有这个问题

_Originally posted by @hushuguo in https://github.com/kwuking/TimeMixer/issues/7#issuecomment-2182855524_

**Comment by hushuguo** [comment]
运行的是ecl和traffic脚本会出问题，我的数据365行，就会出现这个问题。把ECL数据集减少一些就会复现这个问题。

**Comment by kwuking** [comment]
你好请问是执行ecl和traffic脚本吗？我这里测试了是什么问题的，您说的数据量少是什么意思呢？ecl和traffic的数据集是固定的。

**Comment by hushuguo** [comment]
作者，你好。
你可以把traffic数据集删除到2000行左右，然后再跑sh脚本的话，就是出现__len__报错。
