### ISSUE TITLE
大佬们好，首先要感谢昨天的回答。我解决了昨天的问题后，又有新的问题，KeyError: 'Autoformer'是为什么呀？

### ISSUE THREAD

**Issue by DirectorZ1** [kwuking/TimeMixer#44]
Use GPU: cuda:0
Traceback (most recent call last):
  File "d:\code\TimeMixer-main\run.py", line 140, in <module>
    exp = Exp(args)  # set experiments
  File "d:\code\TimeMixer-main\exp\exp_long_term_forecasting.py", line 20, in __init__
    super(Exp_Long_Term_Forecast, self).__init__(args)
  File "d:\code\TimeMixer-main\exp\exp_basic.py", line 13, in __init__
    self.model = self._build_model().to(self.device)
  File "d:\code\TimeMixer-main\exp\exp_long_term_forecasting.py", line 23, in _build_model
    model = self.model_dict[self.args.model].Model(self.args).float()
KeyError: 'Autoformer'

**Comment by kwuking** [comment]
你好，看日志报错是引入了Autoformer模型导致的，目前该代码仓库里并没有包含Autoformer相关内容，如果想要使用Autoformer可以使用我们的[TSLib](https://github.com/thuml/Time-Series-Library)。

**Comment by DirectorZ1** [comment]
> 你好，看日志报错是引入了Autoformer模型导致的，目前该代码仓库里并没有包含Autoformer相关内容，如果想要使用Autoformer可以使用我们的[TSLib](https://github.com/thuml/Time-Series-Library)。

实在是打扰您了，我刚刚入门，代码方面真的是不太懂，感谢您！

**Comment by Vw50hhhhh** [comment]
你好，请问你解决了吗，怎么解决的呀

**Comment by Lu0005** [comment]
您好 请问您解决了吗，具体怎么操作的啊

**Comment by DirectorZ1** [comment]
> 您好 请问您解决了吗，具体怎么操作的啊



> 你好，请问你解决了吗，怎么解决的呀

要把Autoformer改成TimesNet

**Comment by DirectorZ1** [comment]
> 您好 请问您解决了吗，具体怎么操作的啊

要把Autoformer改成TimesNet

**Comment by Lu0005** [comment]
好的谢谢您



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月13日(周二) 中午11:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kwuking/TimeMixer] 大佬们好，首先要感谢昨天的回答。我解决了昨天的问题后，又有新的问题，KeyError: 'Autoformer'是为什么呀？ (Issue #44)




  
您好 请问您解决了吗，具体怎么操作的啊
  
要把Autoformer改成TimesNet
