### ISSUE TITLE
How to add future features to predict

### ISSUE THREAD

**Issue by Zlus-yu** [kwuking/TimeMixer#46]
Hello, thank you very much for providing such excellent work. I am now studying the photovoltaic power prediction and would like to test it with your TimeMixer. I have data in the same format as the ETT dataset, with slightly different feature fields: ['date',...(other features), target feature], here my (other features) are some weather features, such as irradiance, temperature, humidity, etc. target feature is the actual power generation. And the resolution of my dataset is 15min(96 points a day). Now I think, using the historical data of the past 5-10 days (historical weather and historical power), combined with the  weather data of the next 10 days (960 points), to predict the power of the next 10 days (960 points), how can I adjust the input variables of the network? I notice that the model now supports using future temporal features for prediction, but the future temporal features seem to be encoded time series, which I don't quite understand, I think the main factor that affects  power is future weather data, so I want to add future weather data for forecasting power

**Comment by kwuking** [comment]
Thank you for your interest in our work. Currently, TimeMixer supports the addition of future features, such as future weather data. You can refer to the relevant explanations in our README and make slight modifications to the configuration. If you need to operate on a specific private dataset, you will need to add the corresponding dataloader. Please refer to the related implementations in our dataloader for guidance.
