### ISSUE TITLE
想请问下如果把c_out设置为1是不是就可以认为变成了协变量预测任务（MISO）

### ISSUE THREAD

**Issue by IcyTide** [kwuking/TimeMixer#48]
这样做有什么缺陷或者隐患吗

**Comment by IcyTide** [comment]
其他对应的代码也都修改，保证可以运行，只是想问下从模型设计角度有无问题

**Comment by kwuking** [comment]
> 其他对应的代码也都修改，保证可以运行，只是想问下从模型设计角度有无问题

你好，如果进行多变量或者协变量预测，请务必关闭channel_independent选项，确保不同channel变量之间进行交互，此外多元时间预测可以关注我们另一个工作[iTransformer: Inverted Transformers Are Effective for Time Series Forecasting](https://github.com/thuml/iTransformer)，协变量预测可以关注[TimeXer: Empowering Transformers for Time Series Forecasting with Exogenous Variables](https://arxiv.org/abs/2402.19072)。

**Comment by IcyTide** [comment]
好的，感谢
