### ISSUE TITLE
请问各位大佬，用自己的数据集训练都需要改什么呢？

### ISSUE THREAD

**Issue by DirectorZ1** [kwuking/TimeMixer#49]
我在run.py里把root path和data path都换成了自己的数据，执行的时候就会报出
“Traceback (most recent call last):
  File "d:\code\TimeMixer-main\run.py", line 142, in <module>
    exp.train(setting)
  File "d:\code\TimeMixer-main\exp\exp_long_term_forecasting.py", line 101, in train
    vali_data, vali_loader = self._get_data(flag='val')
  File "d:\code\TimeMixer-main\exp\exp_long_term_forecasting.py", line 30, in _get_data
    data_set, data_loader = data_provider(self.args, flag)
  File "d:\code\TimeMixer-main\data_provider\data_factory.py", line 88, in data_provider
    print(flag, len(data_set))
ValueError: __len__() should return >= 0”
的错误。是不是输入的数据集不对？我需要怎么才能换成自己的数据呢？

**Comment by kwuking** [comment]
你好，可以参照我们提供的dataloader中代码编写适合私有数据集的加载器。

**Comment by shanhaiffffff** [comment]
兄弟，解决了吗，我现在也是这个问题

**Comment by kwuking** [comment]
> 兄弟，解决了吗，我现在也是这个问题

你好，我们代码中提供了datafactory和dataloader两个文件，你可以参考我们dataloader中的Dataset_Custom写法即可，或者直接复用可以，需要注意新增的数据集需要再datafactory进行配置添加。

**Comment by shanhaiffffff** [comment]
> > 兄弟，解决了吗，我现在也是这个问题
> 
> 你好，我们代码中提供了datafactory和dataloader两个文件，你可以参考我们dataloader中的Dataset_Custom写法即可，或者直接复用可以，需要注意新增的数据集需要在datafactory文件中进行配置添加。

好的，谢谢你

**Comment by DirectorZ1** [comment]
> 兄弟，解决了吗，我现在也是这个问题

还没有，可以留个联系方式一起探讨吗？q1375302647

**Comment by kwuking** [comment]
> > 兄弟，解决了吗，我现在也是这个问题
> 
> 还没有，可以留个联系方式一起探讨吗？q1375302647

你好可以将相关内容发送邮件给我，邮箱kwuking@163.com

**Comment by kwuking** [comment]
> > 兄弟，解决了吗，我现在也是这个问题
> 
> 还没有，可以留个联系方式一起探讨吗？q1375302647

你好，我看了你发送的数据后，理解你想要解决的问题应该是类似于协变量预测的问题，使用多列时序特征预测最后一列时序，目前TimeMixer还不支持该功能，建议可以使用[TimeXer: Empowering Transformers for Time Series Forecasting with Exogenous Variables](https://arxiv.org/abs/2402.19072)这个工作，专门用于协变量时序预测。

**Comment by carusyte** [comment]
可是paper说支持multivariate，也有[Short-term Forecasting: Multivariate data](https://github.com/kwuking/TimeMixer?tab=readme-ov-file#short-term-forecasting-multivariate-data) 的报告和复现脚本，其实是跟协变量(covariate)不一样的概念吗？(外行小白路过 :pray: ）
