### ISSUE TITLE
请问训练完后如何用模型预测？

### ISSUE THREAD

**Issue by DataAdvisory** [kwuking/TimeMixer#51]
我用23 features+1 OT的数据集训练完模型，请问如何用训练后的模型进行预测？
训练数据集一共是29928 rows * 24 features（including 1 OT），再加上接下来时间的720 rows * 23 features，预测这720 rows的OT值。如果还有什么需要解释的，请告知。

我运行的参数是（如果有什么不恰当的参数还请大佬指正）：
python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ \
  --data_path data.csv  \
  --model_id ECL_96_720 \
  --model TimeMixer \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 720 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 24 \
  --dec_in 24 \
  --c_out 24 \
  --des 'Exp' \
  --itr 1 \
  --d_model 16 \
  --d_ff 32 \
  --batch_size 16 \
  --learning_rate 0.01 \
  --train_epochs 20 \
  --patience 10 \
  --down_sampling_layers 3 \
  --down_sampling_method avg \
  --down_sampling_window 2

下面是test results：
test 5266
test shape: (329, 16, 720, 24) (329, 16, 720, 24)
test shape: (5264, 720, 24) (5264, 720, 24)
mse:0.8916622400283813, mae:0.5131412148475647
rmse:0.9442787170410156, mape:0.629523754119873, mspe:3473186.0

**Comment by kwuking** [comment]
你好，感谢对于我们工作的关注，训练完成之后，直接load模型即可进行推理，相关权重保存在checkpoint文件路径下，可以参考我们的exp文件中的test部分内容。

**Comment by DataAdvisory** [comment]
多谢多谢。学习了一下test部分的内容，也看到了保存结果的pred.npy和true.npy，请问其中保存的是normalized的数值吗？

**Comment by 2001guanhao** [comment]
> 我用23 features+1 OT的数据集训练完模型，请问如何用训练后的模型进行预测？ 训练数据集一共是29928 rows * 24 features（including 1 OT），再加上接下来时间的720 rows * 23 features，预测这720 rows的OT值。如果还有什么需要解释的，请告知。
> 
> 我运行的参数是（如果有什么不恰当的参数还请大佬指正）： python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/ --data_path data.csv --model_id ECL_96_720 --model TimeMixer --data custom --features M --seq_len 96 --label_len 0 --pred_len 720 --e_layers 3 --d_layers 1 --factor 3 --enc_in 24 --dec_in 24 --c_out 24 --des 'Exp' --itr 1 --d_model 16 --d_ff 32 --batch_size 16 --learning_rate 0.01 --train_epochs 20 --patience 10 --down_sampling_layers 3 --down_sampling_method avg --down_sampling_window 2
> 
> 下面是test results： test 5266 test shape: (329, 16, 720, 24) (329, 16, 720, 24) test shape: (5264, 720, 24) (5264, 720, 24) mse:0.8916622400283813, mae:0.5131412148475647 rmse:0.9442787170410156, mape:0.629523754119873, mspe:3473186.0

您好可以借鉴一下您的代码嘛
