### ISSUE TITLE
论文结果复现

### ISSUE THREAD

**Issue by liangzrtvjivo** [kwuking/TimeMixer#52]
感谢您杰出的工作！
我在复现论文结果的时候遇到了一些问题，在复现模型在ETTh1数据集上的结果的时候。我使用了“scripts/long_term_forecast/ETT_script/TimeMixer_ETTh1_unify.sh”复现结果，但是无法复现出论文汇报的结果。结果如下：

96 | mse:0.3798636496067047, mae:0.3998134136199951
192 | mse:0.4348312318325043, mae:0.43236708641052246
336 | mse:0.507748544216156, mae:0.4682999551296234
720 | mse:0.5382081866264343, mae:0.5003705620765686

我已经按照readme重新配置了环境，并且检查了参数设置为论文中汇报的最佳参数，请问可能是哪里出了问题呢？
非常感谢您的帮助！

**Comment by liangzrtvjivo** [comment]
[TimeMixer_ETTh1日志.txt](https://github.com/user-attachments/files/16122449/TimeMixer_ETTh1.txt)
这是我运行时候的日志。
再次感谢您的耐心帮助！

**Comment by liangzrtvjivo** [comment]
[TimeMixer_ETTh1日志.txt](https://github.com/user-attachments/files/16122455/TimeMixer_ETTh1.txt)
这是我运行时候的日志。
再次感谢您的耐心帮助！

**Comment by kwuking** [comment]
> [TimeMixer_ETTh1日志.txt](https://github.com/user-attachments/files/16122455/TimeMixer_ETTh1.txt) 这是我运行时候的日志。 再次感谢您的耐心帮助！

你好，我看了你的运行日志，请问咱们当前运行的python环境，torch和cuda版本是多少呢，使用的GPU型号是多少，从日志看起来似乎没有什么问题，可以和我邮件（kwuking@163.com）联系讨论下具体内容。

**Comment by lou-yimin** [comment]
> [TimeMixer_ETTh1日志.txt](https://github.com/user-attachments/files/16122455/TimeMixer_ETTh1.txt) 这是我运行时候的日志。 再次感谢您的耐心帮助！

你好，你的运行日志中loss感觉并未收敛，我在复现的时候也遇到了同样的情况，请问这为什么会这样呢？

**Comment by liangzrtvjivo** [comment]
你好，后来我邮件询问了作者，作者建议将learning_rate减小到0.001，batch_size减小到16，epoch增加到50。调节完参数以后，跑出来的结果已经跟原文差不多了

**Comment by lou-yimin** [comment]
> 你好，后来我邮件询问了作者，作者建议将learning_rate减小到0.001，batch_size减小到16，epoch增加到50。调节完参数以后，跑出来的结果已经跟原文差不多了

好的感谢，我尝试跑一下。

**Comment by lou-yimin** [comment]
> 你好，后来我邮件询问了作者，作者建议将learning_rate减小到0.001，batch_size减小到16，epoch增加到50。调节完参数以后，跑出来的结果已经跟原文差不多了

你好，我的还是loss下降不明显，训练12个epoch就早停了，到不了50epoch。以下是参数设置，请问可以提供下你的参数设置吗，万分感谢，这是我的邮箱：1298632838@qq.com
`
python -u init_run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path  ./dataset/ETT-small/\
  --data_path ETTh1.csv \
  --model_id ETTh1_96'_'96 \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 96 \
  --e_layers 2 \
  --enc_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --d_model 16 \
  --d_ff 32 \
  --learning_rate 0.001 \
  --train_epochs 50 \
  --patience 10 \
  --batch_size 16 \
  --down_sampling_layers 3 \
  --down_sampling_method avg \
  --down_sampling_window 2 >logs/longterm/$model_name'_96-96_3'.log
`

**Comment by liangzrtvjivo** [comment]
[timemixer_etth1.log](https://github.com/user-attachments/files/17001355/timemixer_etth1.log)
你好，这是我重新跑了一遍的结果。我的理解是，train loss不一定需要达到收敛，收敛也可能会出现过拟合的情况
