### ISSUE TITLE
可视化MLP权重

### ISSUE THREAD

**Issue by Haohongchi** [kwuking/TimeMixer#54]
你好我想问一下图3中的，这种两个线性层加激活函数组成的MLP，权重是如何可视化出来的。

**Comment by kwuking** [comment]
> 你好我想问一下图3中的，这种两个线性层加激活函数组成的MLP，权重是如何可视化出来的。

你好，感谢对于我们工作的关注，您可以使用matplotlib或者seaborn的heatmap进行绘制即可。
