### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by czzdsg** [kwuking/TimeMixer#56]
我想问一下如果用时序特别短的数据是不是训练不了，例如只有月份的17个时间序列。

**Comment by kwuking** [comment]
> 我想问一下如果用时序特别短的数据是不是训练不了，例如只有月份的17个时间序列。

你好，我收到了你的邮件，数据集长度太短确实会有很大的影响，建议数据集长度尽可能不要太短，比如我们输入96预测输出96，长度至少应该是96+96=192的倍数以上比较合适，不然数据太少，难以训练，甚至不满足预测输入输出长度。

**Comment by czzdsg** [comment]
我理解的代码实现过程，假设有10000条时间序列，seq_len为96，label_len为0，pred_len为1。训练过程就是拿百分之70的时间序列逐步按索引从前(0-7000)往后96历史，1预测往里输入训练模型，测试过程就是拿百分之15的时间序列从前往后(7000-8500)96历史输入模型得到1预测值和真实值比较算指标，请问大致是这样实现的吗？万分感谢

**Comment by kwuking** [comment]
> 我理解的代码实现过程，假设有10000条时间序列，seq_len为96，label_len为0，pred_len为1。训练过程就是拿百分之70的时间序列逐步按索引从前(0-7000)往后96历史，1预测往里输入训练模型，测试过程就是拿百分之15的时间序列从前往后(7000-8500)96历史输入模型得到1预测值和真实值比较算指标，请问大致是这样实现的吗？万分感谢

你好，我们是按照dataloader中数据集的划分，划分为训练，验证和测试三部分，其中训练过程中使用训练集和验证集，测试过程中使用测试集，您可以参考我们dataloader中的代码，这部分包含了训练和测试所有过程中数据集的处理内容。
