### ISSUE TITLE
复现问题：RuntimeError

### ISSUE THREAD

**Issue by yulinstudy** [kwuking/TimeMixer#58]
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
        在复现时碰到了这个错误，请问大家有碰到过吗，是怎么解决的？

**Comment by kwuking** [comment]
你好，感谢对于我们工作的关注，您这个问题是由于本地执行没有gpu环境，但是开启了num_workers多线程加载导致的，您可以将num_workers设置为0，并且将use_gpu设置为false即可解决。

**Comment by yulinstudy** [comment]
> 你好，感谢对于我们工作的关注，您这个问题是由于本地执行没有gpu环境，但是开启了num_workers多线程加载导致的，您可以将num_workers设置为0，并且将use_gpu设置为false即可解决。

感谢回答，我调试一下我的gpu环境
