### ISSUE TITLE
求运行环境

### ISSUE THREAD

**Issue by guanfj** [kwuking/TimeMixer#59]
我用miniconda环境管理，但我用python3.9和3.10环境下安装sktime时，均出现错误。
现在弄不清楚什么原因和版本匹配了，请提供一个完整的安装教程，以便我们新手入手学习

**Comment by gy-zkj** [comment]
> 我用miniconda环境管理，但我用python3.9和3.10环境下安装sktime时，均出现错误。 现在弄不清楚什么原因和版本匹配了，请提供一个完整的安装教程，以便我们新手入手学习

我的环境是3.10的，以下版本可以运行
einops                     0.8.0
matplotlib                 3.9.0
numpy                      1.23.5
pandas                     2.2.2
patool                     1.12
reformer-pytorch           1.4.4
scikit-learn               1.5.0
scipy                      1.13.1
sktime                     0.31.0
sympy                      1.12
torch                      1.13.1+cu116
tqdm                       4.65.0

**Comment by guanfj** [comment]
谢谢，已跑起来了

**Comment by guanfj** [comment]
> > 我用miniconda环境管理，但我用python3.9和3.10环境下安装sktime时，均出现错误。 现在弄不清楚什么原因和版本匹配了，请提供一个完整的安装教程，以便我们新手入手学习
> 
> 我的环境是3.10的，以下版本可以运行 einops 0.8.0 matplotlib 3.9.0 numpy 1.23.5 pandas 2.2.2 patool 1.12 reformer-pytorch 1.4.4 scikit-learn 1.5.0 scipy 1.13.1 sktime 0.31.0 sympy 1.12 torch 1.13.1+cu116 tqdm 4.65.0

您好，在您的帮助下，运行环境搭建起来了，非常感谢，但运行示例代码时，出现以下提示：

**Comment by kwuking** [comment]
你好，这个是因为你本地测试没有提供GPU环境导致的，请将use_gpu设置为False，num_workers设置为0，应该就可以了。

**Comment by guanfj** [comment]
非常感谢
