### ISSUE TITLE
大佬们好，想问下KeyError: 'Autoformer'是为什么呀？还是小白，不太懂，感谢各位大佬了 

### ISSUE THREAD

**Issue by Vw50hhhhh** [kwuking/TimeMixer#61]
Use GPU: cuda:0
Traceback (most recent call last):
  File "/mnt/workspace/baseline/project/train.py", line 77, in <module>
    exp = Exp(args)  # set experiments
  File "/mnt/workspace/baseline/project/exp/exp_long_term_forecasting.py", line 17, in __init__
    super(Exp_Long_Term_Forecast, self).__init__(args)
  File "/mnt/workspace/baseline/project/exp/exp_basic.py", line 13, in __init__
    self.model = self._build_model().to(self.device)
  File "/mnt/workspace/baseline/project/exp/exp_long_term_forecasting.py", line 20, in _build_model
    model = self.model_dict[self.args.model].Model(self.args).float()
KeyError: 'Autoformer'

**Comment by mouadenna** [comment]
same error

**Comment by kwuking** [comment]
> Use GPU: cuda:0 Traceback (most recent call last): File "/mnt/workspace/baseline/project/train.py", line 77, in exp = Exp(args) # set experiments File "/mnt/workspace/baseline/project/exp/exp_long_term_forecasting.py", line 17, in **init** super(Exp_Long_Term_Forecast, self).**init**(args) File "/mnt/workspace/baseline/project/exp/exp_basic.py", line 13, in **init** self.model = self._build_model().to(self.device) File "/mnt/workspace/baseline/project/exp/exp_long_term_forecasting.py", line 20, in _build_model model = self.model_dict[self.args.model].Model(self.args).float() KeyError: 'Autoformer'

你好，你需要将exp中模型设置为TimeMixer。

**Comment by kwuking** [comment]
> Use GPU: cuda:0 Traceback (most recent call last): File "/mnt/workspace/baseline/project/train.py", line 77, in exp = Exp(args) # set experiments File "/mnt/workspace/baseline/project/exp/exp_long_term_forecasting.py", line 17, in **init** super(Exp_Long_Term_Forecast, self).**init**(args) File "/mnt/workspace/baseline/project/exp/exp_basic.py", line 13, in **init** self.model = self._build_model().to(self.device) File "/mnt/workspace/baseline/project/exp/exp_long_term_forecasting.py", line 20, in _build_model model = self.model_dict[self.args.model].Model(self.args).float() KeyError: 'Autoformer'

你好，你需要将exp中模型设置为TimeMixer。

**Comment by Vw50hhhhh** [comment]
好的，谢谢！！！
