### ISSUE TITLE
运行时间问题

### ISSUE THREAD

**Issue by Caominjun9** [kwuking/TimeMixer#63]
您好，在遵照experiment scripts中参数，对traffic数据集中的一列进行完整的训练和预测，耗时1h+，我的GPU是4060ti16G，请问这是否是正常的？同样的数据集和配置在informer中跑完只需要几分钟，请问两者效率的差别主要是什么导致的？
感谢！

**Comment by kwuking** [comment]
你好，感谢对于我们工作的关注，这个原因应该是TimeMIxer默认开启了channel independent，channel independent将channel维度变量转移到batch维度上，使得模型训练耗时增加。

**Comment by Caominjun9** [comment]
感谢，修改后确实减少了大量时间，顺带问一下，将channel维度变量转移到batch维度上会对训练和预测结果造成什么样的影响？

**Comment by Caominjun9** [comment]
> 你好，感谢对于我们工作的关注，这个原因应该是TimeMIxer默认开启了channel independent，channel independent将channel维度变量转移到batch维度上，使得模型训练耗时增加。

感谢，修改后确实减少了大量时间，顺带问一下，将channel维度变量转移到batch维度上会对训练和预测结果造成什么样的影响？

**Comment by kwuking** [comment]
> > 你好，感谢对于我们工作的关注，这个原因应该是TimeMIxer默认开启了channel independent，channel independent将channel维度变量转移到batch维度上，使得模型训练耗时增加。
> 
> 感谢，修改后确实减少了大量时间，顺带问一下，将channel维度变量转移到batch维度上会对训练和预测结果造成什么样的影响？

你好，关于在时间序列预测中channel independent的研究可以参考这篇工作[The Capacity and Robustness Trade-off: Revisiting the Channel Independent Strategy for Multivariate Time Series Forecasting](https://arxiv.org/pdf/2304.05206)。

**Comment by kwuking** [comment]
> > 你好，感谢对于我们工作的关注，这个原因应该是TimeMIxer默认开启了channel independent，channel independent将channel维度变量转移到batch维度上，使得模型训练耗时增加。
> 
> 感谢，修改后确实减少了大量时间，顺带问一下，将channel维度变量转移到batch维度上会对训练和预测结果造成什么样的影响？

通常进行channe independent操作对于多元时序预测而言会显著增加训练和推理的时间，从效果而言由于进行了通道独立操作，使得不同时序之间的影响减小，在目前的主流公开数据集上可以有效减少预测误差，具体研究可以参考上条回复中的论文。
