### ISSUE TITLE
test阶段将drop_last设置为True是否会导致测试结果不准确

### ISSUE THREAD

**Issue by huangst21** [kwuking/TimeMixer#64]
作者您好，在data_provider您将drop_last设置为True，且并没有将batch_size设为1，这是否会导致测试结果不准确呢？

**Comment by kwuking** [comment]
你好，感谢你对于我们工作的关注，可以参考TSLib中的设置将batch_size设置为1即可，我们目前遵循informer以来模式进行实验设置。
