### ISSUE TITLE
你好，请问是否能够提供达到论文中超参数搜索后预测结果的超参数

### ISSUE THREAD

**Issue by bigdata0** [kwuking/TimeMixer#67]
TimeMixer的训练速度太慢，尝试了一下部分步长和学习率参数发现还是没法达到论文中的实验结果，请问能够提供一下吗，复现较为困难，非常感谢。

**Comment by bigdata0** [comment]
实验环境应该是没什么问题，关于超参数搜索，请问针对同一个数据集预测不同的步长，除了predict_len不一样，其他参数都是一致的吗，比如采样层数或layer层数，有没有可能出现类似于以下情况：预测96步长和预测192步长的采样层数或学习率等参数不一样。

**Comment by TrilsKnightley** [comment]
> 你好，感谢对于我们工作的关注，TimeMixer应该是非常高效的模型，不知道训练速度太慢是因为下采样层数或者layer层数设置过大嘛，建议使用GPU进行训练，超参数搜索建议参考Appendix E中的内容，其中包含对于超参数搜索的详细介绍，后续按照您的建议我也会尝试整理相关内容以及尝试发布预训练模型权重，方便大家使用，再次感谢您的建议。

大佬尽快发布呀<3
