### ISSUE TITLE
Questions about hyperparameters.

### ISSUE THREAD

**Issue by iDestro** [kwuking/TimeMixer#68]
Hello, thank you very much for providing such excellent work.
Can you provide the optimal hyperparameters of the baseline model after hyperparameter search?

**Comment by kwuking** [comment]
Thank you for your suggestion. We will consider organizing it. We will also try to release the pre-trained model and Docker image environment in the future, but this might take some time. We have been extremely busy lately. Once we make progress, we will publish updates on our homepage.
