### ISSUE TITLE
bash scripts/scripts/short_term_forecast/M4/TimeMixer.sh

### ISSUE THREAD

**Issue by rbm123456** [kwuking/TimeMixer#71]
Why do the following errors occur when the m4 script file is run:
![a9444cda-d7da-497d-8280-dafa748aa94a](https://github.com/user-attachments/assets/a6eb407e-6885-472b-8db2-e8b59943e090)

**Comment by kwuking** [comment]
Hi, thank you for your attention to our work. This issue might be related to the NumPy version. You can try downgrading NumPy to version 1.23.0, which should resolve the problem. Please give it a try.

**Comment by rbm123456** [comment]
> 您好，感谢您对我们工作的关注。此问题可能与 NumPy 版本有关。您可以尝试将 NumPy 降级到版本 1.23.0，这应该可以解决问题。请试一试。

好的，非常感谢，已经解决了，麻烦你还能再问一下就是那个线性层的权重图怎么画呀，就是下面这个图
![Uploading motivation1.png…]()

**Comment by rbm123456** [comment]
> Hi, thank you for your attention to our work. This issue might be related to the NumPy version. You can try downgrading NumPy to version 1.23.0, which should resolve the problem. Please give it a try.

Ok, thank you very much, that's settled, but can you ask me again how to draw the weight graph of the linear layer, which is the graph below
![Uploading motivation1.png…]()

**Comment by rbm123456** [comment]
> Hi, thank you for your attention to our work. This issue might be related to the NumPy version. You can try downgrading NumPy to version 1.23.0, which should resolve the problem. Please give it a try.
Ok, thank you very much, that's settled, but can you ask me again how to draw the weight graph of the linear layer, which is the graph below
![Uploading c80d8276-29d7-4602-a67f-09bae2af2c9c.png…]()
