### ISSUE TITLE
Inquiry about multivariate / covariate / endogenous / exogenous variable support

### ISSUE THREAD

**Issue by carusyte** [kwuking/TimeMixer#72]
There're already quite some inquires or latent demand on such feature(s), albeit I'm possibly not summarizing it in academically precise manner:

#24 How to add future covariates
#49 请问各位大佬，用自己的数据集训练都需要改什么呢？
#73 TimeMixer是否适合私有数据集的协变量预测任务？
Nixtla/neuralforecast#1137 TimeMixer Model - exogeneous variables support

**Comment by carusyte** [comment]
Take the multivariate dataset PEMS08 for example. It has the shape (17856, 170, 3), I'd assume it means (batch, number of detectors, variates), whereby the variates may include flow, occupy, and speed, per this [kaggle notebook](https://www.kaggle.com/code/jvthunder/pems08-traffic-flow-prediction).

However, as I debug into the `exp_long_term_forecasting.py`, turns out that the `batch_x.shape` becomes (32, 96, 170), for which I'd assume meaning (batch, seq_len, variate). It seems that only one of the multiple variates (in this case 3) is used for training the model.

**Comment by kwuking** [comment]
Thanks for your attention to our work. I apologize for not understanding your specific meaning. TimeMixer for the PEMS dataset is a multivariate time series prediction, which means it processes multiple time series simultaneously.
