### ISSUE TITLE
TimeMixer是否适合私有数据集的协变量预测任务？

### ISSUE THREAD

**Issue by Meatone0125** [kwuking/TimeMixer#73]
你好，感谢你们的贡献。
现在我自己制作了一个数据集，主要目的是利用特征变量abc，预测d的一个二分类任务。数据集是由多个客户的历史数据组成，因此每个客户对应的历史数据数量，数据间的时间间隔存在差异。因此TimeMixer是否适用于该任务，我存在疑惑。不知道TimeMixer是否适合用于这个任务场景。其中channel_independent的设置，以及data_loader中Dataset_Custom有哪些部分是需要修改的，我存在一些疑问。
非常期待你的回答，万分感谢！

**Comment by Meatone0125** [comment]
补充：数据集是由多个客户的历史数据组成，因此每个客户对应的历史数据，时间间隔存在差异。因此TimeMixer是否适用于该任务，我存在疑惑。

**Comment by kwuking** [comment]
你好，非常感谢对于我们工作的关注，如果您使用个人数据集，如果您做多变量预测，您需要channel_independent设置为0，关闭通道独立，您需要使用您个人的data_loader，可以参考我们Dataset_Custom的代码进行构建。
