### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by wtt6668888** [kwuking/TimeMixer#74]
RuntimeError: The size of tensor a (96) must match the size of tensor b (144) at non-singleton dimension 1

**Comment by Mumout01** [comment]
> RuntimeError: The size of tensor a (96) must match the size of tensor b (144) at non-singleton dimension 1
You need to set label_len=0

**Comment by kwuking** [comment]
> RuntimeError: The size of tensor a (96) must match the size of tensor b (144) at non-singleton dimension 1

Thanks to attention for out work. Could you please provide the detailed log and specific scripts?

**Comment by sunny0315** [comment]
![image](https://github.com/user-attachments/assets/f6d1ce84-21ef-4505-b827-0c9069e23483)

TimeMixer_unify.sh :
model_name=TimeMixer

seq_len=30
e_layers=3
down_sampling_layers=3
down_sampling_window=2
learning_rate=0.01
d_model=32
d_ff=64
batch_size=16


python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path train_test_data.csv \
  --model_id Traffic_$seq_len'_'10 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len $seq_len \
  --label_len 0 \
  --pred_len 10 \
  --e_layers $e_layers \
  --d_layers 1 \
  --factor 3 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 6 \
  --des 'Exp' \
  --itr 1 \
  --d_model $d_model \
  --d_ff $d_ff \
  --batch_size $batch_size \
  --learning_rate $learning_rate \
  --down_sampling_layers $down_sampling_layers \
  --down_sampling_method avg \
  --down_sampling_window $down_sampling_window

**Comment by jianzi123** [comment]
I met the same problem, @wtt6668888 please check label_len set, default value is 48, and 96+48=144
