### ISSUE TITLE
a UnicodeDecodeError while using sktime

### ISSUE THREAD

**Issue by fenixzml** [kwuking/TimeMixer#78]
I encountered a UnicodeDecodeError while using sktime in my project. The error seems to be related to the default encoding used when reading a file in the sktime.utils._estimator_html_repr module. Here are the details:

\TimeMixer-main\.venv\Lib\site-packages\sktime\utils\_estimator_html_repr.py", line 190, in <module>
    _STYLE = style_file.read()
             ^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb8 in position 4507: illegal multibyte sequence

**Comment by kwuking** [comment]
Many thanks for your attention to our work. You need to use 'UTF-8' code for this code.
