### ISSUE TITLE
无法运行README中的bash文件

### ISSUE THREAD

**Issue by hucc1123** [kwuking/TimeMixer#79]
作者你好 我在尝试运行README中的bash文件出现如下报错，请问该如何解决

(timemixer) D:\Pycharm\Project directory\TimeMixer-copy>bash ./scripts/long_term_forecast/ETT_script/TimeMixer_ETTm1.shbash ./scripts/long_term_forecast/ECL_script/TimeMixer.shbash ./scripts/long_term_forecast/Traffic_script/TimeMixer.shbash ./scripts/long_term_forecast/Solar_script/TimeMixer.shbash ./scripts/long_term_forecast/Weather_script/TimeMixer.shbash ./scripts/short_term_forecast/M4/TimeMixer.shbash ./scripts/short_term_forecast/PEMS/TimeMixer.sh
'bash' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by kwuking** [comment]
你好，你需要先确保你的环境中有bash，如果是windows系统建议安装git，或者更换linux或Mac
