### ISSUE TITLE
TimeMixer代码里没有N-Beats那种backcast prediction吧？

### ISSUE THREAD

**Issue by mz24cn** [kwuking/TimeMixer#80]
我看了长短期exp的代码，只有长短期预测任务中，引用了dec_inp。dec_inp中包含了label_len的过去数据。
dec_inp传递给TimeMixer.py的forecast的x_dec参数，而x_dec参数根本没用上。
把dec_inp这个参数设置成None，训练过程完全一样不受影响。
保留根本没用上的label_len的过去标签数据是为了方便用其他模型跑测试做对比还是怎么的？

**Comment by kwuking** [comment]
你好，感谢对于我们工作的关注，目前是没有使用的，框架整体使用的[TSLib框架](https://github.com/thuml/Time-Series-Library)，代码风格保持了统一。
