### ISSUE TITLE
channel_independence=0/1

### ISSUE THREAD

**Issue by fffffffuuuuuccckkk** [kwuking/TimeMixer#81]
作者你好，请问在这篇文章中channel_independence=0/1的区别在哪些部分呢？因为原文应该并没有计算通道相关性，但是在TimeMixer.py中可以不执行通道独立

**Comment by kwuking** [comment]
感谢对于我们工作的关注，channel_independence是patchTST提出来一个提升模型性能效果trick，并不涉及模型架构本身，因此我们在TimeMixer把他作为一个可以开启关闭的参数，方便大家使用。

**Comment by fffffffuuuuuccckkk** [comment]
> 感谢对于我们工作的关注，channel_independence是patchTST提出来一个提升模型性能效果trick，并不涉及模型架构本身，因此我们在TimeMixer把他作为一个可以开启关闭的参数，方便大家使用。

感谢您的回复，我尝试关闭channel_independence，得到较差的结果，请问关闭channel_independence后模型在哪些部分对多通道输入执行了与channel_independence不同的操作呢
