### ISSUE TITLE
The script execution error for Short_term_forecast.

### ISSUE THREAD

**Issue by 125763** [kwuking/TimeMixer#82]
1.When executing the short_time_forecast, running the script ./scripts/short_term_forecast/M4/TimeMixer.sh，results in the following error: ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimension. The detected shape was (414,) + inhomogeneous part.

**Comment by kwuking** [comment]
Hi, thank you for your attention to our work. This issue might be related to the NumPy version. You can try downgrading NumPy to version 1.23.0, which should resolve the problem. Please give it a try.
