### ISSUE TITLE
NSE和R2较低

### ISSUE THREAD

**Issue by TrilsKnightley** [kwuking/TimeMixer#87]
添加了NSE和R2两个指标，用自己的数据集跑了结果只有0.5, 0.6，而且论文中也没有涉及这两个指标，请问是TimeMixer普遍在NSE和R2表现不好吗？

**Comment by kwuking** [comment]
你好，感谢对于我们工作的关注，目前时间序列通常采用的指标主要是MSE，MAE，MAPE等指标，我不是很了解NSE和R2这两个指标，因此我没有测试过这两个指标。
