### ISSUE TITLE
Hyperparameter Search

### ISSUE THREAD

**Issue by Chenxan** [kwuking/TimeMixer#91]
Thank you very much for your contributions to the field of time series forecasting, which have given us the opportunity to engage with such work. After carefully reading your paper, I have a minor question: the choice of hyperparameters indeed has a significant impact on model performance. Could you please share which method you used for hyperparameter search in the research reported in this paper? This would be a very valuable lesson for us. Thank you!

**Comment by kwuking** [comment]
Many thanks for your interest in our work. We have provided some ranges for hyperparameter tuning in Appendix E, which you can use as a reference.
